### PR TITLE
Adding a sending email guide using ses

### PR DESCRIPTION
**Pull request by shouston3**
-  [x] Amazon SES setup
- [x] Phoenix Application setup
- [x] Testing implementation
- [x] Moving out of your testing environment
- [x] Upload images

Relates to #12

### CODE REVIEW

**Comment by shouston3** [comment]
@nelsonic Feel free to review, I'm still to add some images for the steps

**Comment by nelsonic** [comment]
@shouston3 sorry for not making this clear earlier... 
https://github.com/dwyl/contributing#images-and-binary-files
we tend to drag-and-drop all images into comments and then use the resulting uploaded image in our markdown to _avoid_ clogging up the repo(s) with large binary files ...

**Comment by nelsonic** [comment]
@shouston3 if you merge master into this branch it should pass CI and we can merge. 👍

**Comment by nelsonic** [comment]
@shouston3 thanks for making those updates. Merging ✅ 
CC: @katbow && @iteles for HL 👍

**Pull request merged**
